language: objective-c
osx_image: xcode7.2
script:
  - set -o pipefail && xcodebuild test -project QuickResponse.xcodeproj -scheme QuickResponse -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.2" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)

